// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZettelWeb.Data;

#nullable disable

namespace ZettelWeb.Data.Migrations
{
    [DbContext(typeof(ZettelDbContext))]
    [Migration("20260222141707_AddContentGenerator")]
    partial class AddContentGenerator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZettelWeb.Models.ContentGeneration", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.PrimitiveCollection<string>("ClusterNoteIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeedNoteId")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.PrimitiveCollection<float[]>("TopicEmbedding")
                        .HasColumnType("real[]");

                    b.Property<string>("TopicSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentGenerations");
                });

            modelBuilder.Entity("ZettelWeb.Models.ContentPiece", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenerationId")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.HasIndex("Status");

                    b.ToTable("ContentPieces");
                });

            modelBuilder.Entity("ZettelWeb.Models.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbedError")
                        .HasColumnType("text");

                    b.Property<int>("EmbedRetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("EmbedStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("EmbedUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<float[]>("Embedding")
                        .HasColumnType("real[]");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EnrichRetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("EnrichStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("None");

                    b.Property<string>("EnrichmentJson")
                        .HasColumnType("text");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Regular");

                    b.Property<string>("Source")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceAuthor")
                        .HasColumnType("text");

                    b.Property<string>("SourceTitle")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<int?>("SourceYear")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Permanent");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("ZettelWeb.Models.NoteTag", b =>
                {
                    b.Property<string>("NoteId")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.HasKey("NoteId", "Tag");

                    b.ToTable("NoteTags");
                });

            modelBuilder.Entity("ZettelWeb.Models.NoteVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoteId")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("NoteVersions");
                });

            modelBuilder.Entity("ZettelWeb.Models.UsedSeedNote", b =>
                {
                    b.Property<string>("NoteId")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NoteId");

                    b.ToTable("UsedSeedNotes");
                });

            modelBuilder.Entity("ZettelWeb.Models.VoiceConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StyleNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Medium");

                    b.ToTable("VoiceConfigs");
                });

            modelBuilder.Entity("ZettelWeb.Models.VoiceExample", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Medium");

                    b.ToTable("VoiceExamples");
                });

            modelBuilder.Entity("ZettelWeb.Models.ContentPiece", b =>
                {
                    b.HasOne("ZettelWeb.Models.ContentGeneration", null)
                        .WithMany("Pieces")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZettelWeb.Models.NoteTag", b =>
                {
                    b.HasOne("ZettelWeb.Models.Note", null)
                        .WithMany("Tags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZettelWeb.Models.NoteVersion", b =>
                {
                    b.HasOne("ZettelWeb.Models.Note", null)
                        .WithMany("Versions")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZettelWeb.Models.ContentGeneration", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("ZettelWeb.Models.Note", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
